# Generated by Django 3.1.1 on 2020-10-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200928_1456'),
        ('notification', '0002_customnotification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='customnotification',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
