# Generated by Django 3.1.1 on 2020-10-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201005_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ssid',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
