# Generated by Django 3.1.1 on 2020-09-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
