# Generated by Django 3.1.1 on 2020-09-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='default_cover.jpg', upload_to='profile_pics'),
        ),
    ]
